export const CURRENCIES = [
  { code: 'USD', name: 'US Dollar', symbol: '$', countryCode: 'US' },
  { code: 'EUR', name: 'Euro', symbol: '€', countryCode: 'EU' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', countryCode: 'JP' },
  { code: 'GBP', name: 'British Pound Sterling', symbol: '£', countryCode: 'GB' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', countryCode: 'AU' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', countryCode: 'CA' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', countryCode: 'CH' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', countryCode: 'CN' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', countryCode: 'SE' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', countryCode: 'NZ' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', countryCode: 'KR' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', countryCode: 'SG' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', countryCode: 'NO' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'Mex$', countryCode: 'MX' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', countryCode: 'IN' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', countryCode: 'RU' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', countryCode: 'BR' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', countryCode: 'ZA' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', countryCode: 'TR' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', countryCode: 'EG' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', countryCode: 'KZ' },
  { code: 'UZS', name: 'Uzbekistan Som', symbol: 'Soʻm', countryCode: 'UZ' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'С̲', countryCode: 'KG' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', countryCode: 'GE' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', countryCode: 'AZ' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', countryCode: 'BY' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', countryCode: 'UA' },
  { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', countryCode: 'PL' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', countryCode: 'TH' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', countryCode: 'ID' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', countryCode: 'MY' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', countryCode: 'PH' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', countryCode: 'VN' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', countryCode: 'BD' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', countryCode: 'PK' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', countryCode: 'IR' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', countryCode: 'SA' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', countryCode: 'AE' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', countryCode: 'QA' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', countryCode: 'KW' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'ب.د', countryCode: 'BH' },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼', countryCode: 'OM' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', countryCode: 'JO' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', countryCode: 'LB' },
  { code: 'SYP', name: 'Syrian Pound', symbol: 'ل.س', countryCode: 'SY' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', countryCode: 'IQ' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', countryCode: 'YE' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'රු', countryCode: 'LK' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', countryCode: 'NP' },
  { code: 'MNT', name: 'Mongolian Tögrög', symbol: '₮', countryCode: 'MN' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', countryCode: 'MM' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', countryCode: 'LA' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', countryCode: 'KH' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', countryCode: 'AL' },
  { code: 'BAM', name: 'Bosnia and Herzegovina Convertible Mark', symbol: 'KM', countryCode: 'BA' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', countryCode: 'BG' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', countryCode: 'CZ' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', countryCode: 'DK' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', countryCode: 'IS' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', countryCode: 'HU' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', countryCode: 'MD' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'L', countryCode: 'RO' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин', countryCode: 'RS' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', countryCode: 'HR' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', countryCode: 'MK' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', countryCode: 'GH' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', countryCode: 'KE' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', countryCode: 'NG' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', countryCode: 'TZ' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', countryCode: 'UG' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', countryCode: 'ZM' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$', countryCode: 'ZW' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', countryCode: 'AR' },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CLP$', countryCode: 'CL' },
  { code: 'COP', name: 'Colombian Peso', symbol: 'COP$', countryCode: 'CO' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.', countryCode: 'PE' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', countryCode: 'UY' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.S', countryCode: 'VE' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', countryCode: 'CR' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '₱', countryCode: 'CU' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', countryCode: 'DO' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', countryCode: 'GT' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', countryCode: 'HN' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', countryCode: 'HT' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', countryCode: 'JM' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', countryCode: 'NI' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', countryCode: 'PA' },
  { code: 'PYG', name: 'Paraguayan Guaraní', symbol: '₲', countryCode: 'PY' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', countryCode: 'TT' },
];

export const getCurrencySymbolByCode = (code) => {
  const currencyObj = CURRENCIES.find(c => c.code === code);
  return currencyObj ? currencyObj.symbol : '₽';
};